#### Exercício de predição de vinhos tinto e/ou branco

In [2]:
# carregando os dados
import pandas as pd
df = pd.read_csv('data/wine_dataset.csv')
df.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

In [3]:
# gostariamos de classificar os vinhos em tinto (red) ou branco (white)
# porém, o pandas aceita apenas numeros, logo, trocar red por 0 (zero)
# e white por 1 (um).
# trocando apenas na coluna style e usando a função raplace
df['style'] = df['style'].replace('red', 0)
df['style'] = df['style'].replace('white', 1)

In [4]:
# conferindo se alterou a coluna style
df.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0

In [12]:
# gostariamos de prever se é tinto ou branco, assim, nossa variável alvo (Y) é a coluna style
# o preditores é a variável (x) é todo o resto dos dados, logo, removendo a coluna style (variável alvo)
y = df['style']
x = df.drop('style', axis = 1) #axis=1 (colunas)
print('A variável y é: \n%s\n'%y)
print('A variável x é: \n%s\n'%x)

A variável y é:
0       0
1       0
2       0
3       0
4       0
       ..
6492    1
6493    1
6494    1
6495    1
6496    1
Name: style, Length: 6497, dtype: int64

A variável x é:
      fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
0               7.4              0.70         0.00             1.9      0.076
1               7.8              0.88         0.00             2.6      0.098
2               7.8              0.76         0.04             2.3      0.092
3              11.2              0.28         0.56             1.9      0.075
4               7.4              0.70         0.00             1.9      0.076
...             ...               ...          ...             ...        ...
6492            6.2              0.21         0.29             1.6      0.039
6493            6.6              0.32         0.36             8.0      0.047
6494            6.5              0.24         0.19             1.2      0.041
6495            5.5              0.29         0.30             1.1      0.022
6496            6.0              0.21         0.38             0.8      0.020

      free_sulfur_dioxide  total_sulfur_dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56
1                    25.0                  67.0  0.99680  3.20       0.68
2                    15.0                  54.0  0.99700  3.26       0.65
3                    17.0                  60.0  0.99800  3.16       0.58
4                    11.0                  34.0  0.99780  3.51       0.56
...                   ...                   ...      ...   ...        ...
6492                 24.0                  92.0  0.99114  3.27       0.50
6493                 57.0                 168.0  0.99490  3.15       0.46
6494                 30.0                 111.0  0.99254  2.99       0.46
6495                 20.0                 110.0  0.98869  3.34       0.38
6496                 22.0                  98.0  0.98941  3.26       0.32

      alcohol  quality
0         9.4        5
1         9.8        5
2         9.8        5
3         9.8        6
4         9.4        5
...       ...      ...
6492     11.2        6
6493      9.6        5
6494      9.4        6
6495     12.8        7
6496     11.8        6

[6497 rows x 12 columns]

In [13]:
# no machine learning, importante separar os dados em conjuntos de treinos e teste
# assim, utilizamos o sklearn para tal função
from sklearn.model_selection import train_test_split

#criando os conjuntos de datos de treino e teste:
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size = 0.3) # tamanho especifico para teste, no caso, 30%

In [14]:
# agora, após os tratamentos dos dados, utilizaremos o algoritmo de ML ExtraTreeClassifier
from sklearn.ensemble import ExtraTreesClassifier

# criação do modelo:
modelo = ExtraTreesClassifier() # chamada da função
modelo.fit(x_treino, y_treino) # treinar o algoritmo

# imprimindo os resultados:
resultado = modelo.score(x_teste, y_teste) # comparou os teste com os resultados do treino 
print('Acurácia: \n%s\n'%resultado)

Acurácia:
0.9974358974358974

In [15]:
# fazendo teste
y_teste[500:510]

4784    1
2807    1
2213    1
1592    0
6036    1
5346    1
4964    1
5089    1
2999    1
245     0
Name: style, dtype: int64

In [16]:
x_teste[500:510]

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
4784,6.5,0.21,0.40,7.30,0.041,49.0,115.0,0.99268,3.21,0.43,11.00,6
2807,6.3,0.21,0.40,1.70,0.031,48.0,134.0,0.99170,3.42,0.49,11.50,6
2213,7.5,0.21,0.68,10.90,0.045,38.0,133.0,0.99780,3.00,0.36,8.70,5
1592,6.3,0.51,0.13,2.30,0.076,29.0,40.0,0.99574,3.42,0.75,11.00,6
6036,6.5,0.29,0.30,9.15,0.051,25.0,166.0,0.99339,3.24,0.56,11.35,6
5346,6.8,0.22,0.30,10.60,0.070,67.0,194.0,0.99654,2.89,0.42,9.00,6
4964,7.6,0.20,0.26,4.80,0.033,26.0,76.0,0.99076,2.98,0.49,12.30,7
5089,7.6,0.31,0.24,1.80,0.037,39.0,150.0,0.99130,3.05,0.44,11.80,7
2999,7.3,0.25,0.36,13.10,0.050,35.0,200.0,0.99860,3.04,0.46,8.90,7
245,7.3,0.66,0.00,2.00,0.084,6.0,23.0,0.99830,3.61,0.96,9.90,6

In [17]:
# fazendo predição
previsao = modelo.predict(x_teste[500:510])
print('a previsão é: \n%s\n'%previsao)

a previsão é:
[1 1 1 0 1 1 1 1 1 0]